### ISSUE TITLE
What's the Plus edition？

### ISSUE THREAD

**Issue by GamePlusOne** [PixelExperience-Devices/device_xiaomi_dipper#3]
I want to download the plus edition package,but I don't know what's different about this version.

**Comment by GamePlusOne** [comment]
I want to download the plus edition package,but I don't know what's different about this version.

**Comment by ChinaVRally** [comment]
I want to konw that....

**Comment by Hlcpereira** [comment]
In the most minimal works: The only diff between Plus and Standard Editions are the amount of features. While the Standard Edition has the aim of offering the closest of Pixel ROM stock as we can, the Plus Edition offers some more features, trying to keep the must polished as we can.

**Comment by ChinaVRally** [comment]
Thanks for your help

**Comment by GamePlusOne** [comment]
Thanks for your help
